name: Dockerfile linter

on:
  workflow_dispatch:

jobs:
  hadolist:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-actions@v3.1.0
        with:
          dockerfile: Dockerfile
      - run: 